// Code generated by MockGen. DO NOT EDIT.
// Source: httpClient/client.go

// Package httpClient is a generated GoMock package.
package httpClient

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockHttpDoer is a mock of HttpDoer interface.
type MockHttpDoer struct {
	ctrl     *gomock.Controller
	recorder *MockHttpDoerMockRecorder
}

// MockHttpDoerMockRecorder is the mock recorder for MockHttpDoer.
type MockHttpDoerMockRecorder struct {
	mock *MockHttpDoer
}

// NewMockHttpDoer creates a new mock instance.
func NewMockHttpDoer(ctrl *gomock.Controller) *MockHttpDoer {
	mock := &MockHttpDoer{ctrl: ctrl}
	mock.recorder = &MockHttpDoerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHttpDoer) EXPECT() *MockHttpDoerMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockHttpDoer) Do(req *http.Request) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", req)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockHttpDoerMockRecorder) Do(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockHttpDoer)(nil).Do), req)
}
